### ISSUE TITLE
Be helpful is there was something in the header to help me get to me account, schedule, favs

### ISSUE THREAD

**Issue by saragibby** [ThatConference/that.us#102]
When I went to the site this morning it seemed like I was logged in cause I didn't see the logout option, but no way to quickly get to the sessions I created or my favorites. Be nice to have some nav option like on the sub-pages to get me to those things

<img width="1324" alt="THAT_Schedule___THAT_us" src="https://user-images.githubusercontent.com/82035/87793792-ba139200-c813-11ea-8e45-494d1270c06e.png">

**Comment by csell5** [comment]
I was actually hiding it there on purpose... but noted.
