### ISSUE TITLE
Base for blog?

### ISSUE THREAD

**Issue by boehs** [ThatConference/that.us#1052]
I see in https://github.com/ThatConference/that.us/blob/master/src/_blog/getPosts.js you are using js that looks awfully familiar, because I am also using it! I am trying to track down it's original origin but not sure where it could be. Do you happen to know?

**Comment by csell5** [comment]
@boehs there are a few folks who came up with this pattern. Check out @rodneylab who's doing some amazing work - https://github.com/rodneylab/sveltekit-blog-mdx I originally saw @mattjennings template here https://github.com/mattjennings/sveltekit-blog-template

**Comment by boehs** [comment]
Thanks so much! that was it!
