### ISSUE TITLE
WI 2022 Logo Font not displaying properly

### ISSUE THREAD

**Issue by tsidel** [ThatConference/that.us#1060]
**Describe the bug**
In Thumbnails and on the main page (https://that.us/events/wi/2022/) the THAT Wisconsin logo is asking for a font that is not loading on the page. (The file by itself: https://storage.googleapis.com/that-bucket/eventLogos/that-logo-states-wi-2022.svg)

**To Reproduce**
1. Go to https://storage.googleapis.com/that-bucket/eventLogos/that-logo-states-wi-2022.svg
2. View logo, "Wisconsin Dells, 2022" type is overlapping itself

**Expected behavior**
Type face in the logo should be clear and easy to read. (See https://storage.googleapis.com/that-bucket/eventLogos/that-logo-states-tx-2022.svg for a version that is appearing properly)

**Screenshots**
<img width="251" alt="THAT-WI-Logo-2022" src="https://user-images.githubusercontent.com/194128/139323462-53c08b55-1985-4dc9-8c21-afd928ade61f.png">

**Desktop (please complete the following information):**
 - OS: Mac Big Sur 11.06
 - Browser: Chrome
 - Version: 93
(Also checked Firefox 72, Safari 14)

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: 15.0.1
 - Browser chrome
 - Version unknown

**Additional context**

**Comment by csell5** [comment]
@brettski actually fixed it last night.
