### ISSUE TITLE
On desktop screen, background trees overlaps footer links and renders them unclickable

### ISSUE THREAD

**Issue by tsidel** [ThatConference/that.us#1085]
**Describe the bug**
If you make your browser window smaller, the background svg trees can overlap the footer links and lay on top of them, rendering them unclickable.

**To Reproduce**
1. Go to https://that.us/
2. Make the height of your browser window smaller. You should see the background trees reduce in size.
3. Scroll down to the footer
4. The top row of links are unclickable because the svg is laying on top of them.

**Expected behavior**
Footer links should always be clickable.

**Screenshots**
<img width="1284" alt="Screen Shot 2021-11-14 at 4 48 53 PM" src="https://user-images.githubusercontent.com/194128/141701784-1b756c2f-be31-495f-91a7-4014dc92214c.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 93

**Additional context**
I think this could be solved by adding a higher z-index on the <footer> but then you may need to remove the background colors for this to work.

**Comment by ategen3rt** [comment]
I took a peek in chrome on a PC.  This appears fine.  Maybe fixed already?

**Comment by tsidel** [comment]
I'm able to still recreate it. Maybe it's just a mac/chrome issue.

**Comment by ategen3rt** [comment]
It could also have been me

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
