### ISSUE TITLE
case collision

### ISSUE THREAD

**Issue by csell5** [ThatConference/that.us#1095]
Receiving objects: 100% (14330/14330), 22.44 MiB | 7.52 MiB/s, done.
Resolving deltas: 100% (9334/9334), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'src/routes/support/Code-Of-Conduct.md'
  'src/routes/support/code-of-conduct.md'
  'src/routes/support/Privacy-Policy.md'
  'src/routes/support/privacy-policy.md'
  'src/routes/support/Terms-Of-Use.md'
  'src/routes/support/terms-of-use.md'

**Comment by zaudtke** [comment]
Appears to be resolved.  Closing.
