### ISSUE TITLE
Workshop tickets don't show under /my tickets

### ISSUE THREAD

**Issue by brettski** [ThatConference/that.us#1269]
**Describe the bug**
Members who have a three day and workshop (pre-conference) ticket only have the three-day ticket showing. The workshop ticket doesn't show under that view: https://that.us/my/settings/tickets/ 

**To Reproduce**
Login with an account with a workshop ticket
go to https://that.us/my/settings/tickets/
noticed that the workshop ticket isn't shown

**Expected behavior**
The workshop ticket should show.

**Additional context**
This was reported in the wi/2022 event. Not tested in other events.

**Comment by csell5** [comment]
@brettski I guess we did know about this

**Comment by csell5** [comment]
fixed: #1415
