### ISSUE TITLE
Edit Activity: Supporting Resource links not working when using URLs with query paramaters

### ISSUE THREAD

**Issue by garciadev** [ThatConference/that.us#1280]
When adding Supporting Resources to an activity, the URLs do not work when adding a URL with query paramaters.

**To Reproduce**

1. Log into THAT.us
2. Edit an activity
3. Add a Supporting Resource link that has query params
4. Save
5. View the activity and try clicking the link, the URL will not work as expected.

As an example link, I tried adding a Google Drive link to my presentation:

https://drive.google.com/file/d/1dbB5dM2zZHnAioq65HzarPVnVMYORn15/view?usp=sharing

**Expected behavior**
Adding a link should go to that link properly regardless of query params.

**Additional context**
I noticed the same behavior on desktop and mobile.

**Comment by csell5** [comment]
@allcontributors please add @garciadev for bug
