### ISSUE TITLE
I should be able to remove/delete/cancel a session

### ISSUE THREAD

**Issue by GeekOnCoffee** [ThatConference/that.us#140]

**Comment by brettski** [comment]
With commit, 0af4bbc, I am unable to edit a session, The following error is received in console:
```
SessionForm.svelte:154 Uncaught (in promise) TypeError: Cannot read property 'startTime' of null
    at Array.canCancelSessionAction (SessionForm.svelte:154)
    at Array.create_default_slot$A (SessionForm.svelte:441)
    at create_slot (index.mjs:58)
    at create_fragment$$ (Form.svelte:140)
    at init (index.mjs:1447)
    at new Form (Form.svelte:131)
    at create_fragment$1q (SessionForm.svelte:181)
    at init (index.mjs:1447)
    at new SessionForm (SessionForm.svelte:93)
    at create_then_block$5 (Create.svelte:34)
```

I was initially able to edit one session. I clicked the cancel/withdraw button and have not been able to edit another session. I think the issue is that you can't edit a withdrawn session.

**Comment by brettski** [comment]
The **cancel/withdraw** button is confusing as there is no way off the edit screen and clicking that button to "Cancel" editing with withdraw the session. @csell5

**Comment by csell5** [comment]
So before.. Cancel just reset the form. the only way "off" was the top nav. What interaction were you expecting? Ironically the same is true here in github.. action buttons at the bottom, nav across the top.

**Comment by csell5** [comment]
As for the bug above.. yea. that's all due to the states of a session and not handing things well. we will address that next.

**Comment by brettski** [comment]
> So before.. Cancel just reset the form. the only way "off" was the top nav. What interaction were you expecting? Ironically the same is true here in github.. action buttons at the bottom, nav across the top.

So perhaps remove the work "cancel" and only have withdraw...?...

I pushed an update to the branch changing the formatting of the date in the edit form. Remove the format line if you don't like it.

**Comment by csell5** [comment]
Added.. And renamed to `Cancel / Withdraw`
