### ISSUE TITLE
tidio - seems to cause issues on mobile.

### ISSUE THREAD

**Issue by csell5** [ThatConference/that.us#146]
![Screenshot_20200722-075845_Chrome](https://user-images.githubusercontent.com/240650/88179355-64632f00-cbf1-11ea-9c67-01b444d31061.jpg)
![Screenshot_20200722-075851_Chrome](https://user-images.githubusercontent.com/240650/88179361-662cf280-cbf1-11ea-91a5-44246822a4df.jpg)

_Originally posted by @GeekOnCoffee in https://github.com/ThatConference/that.us/pull/145#issuecomment-662438605_

**Comment by brettski** [comment]
Didn't even show on my phone (Brave)

**Comment by brettski** [comment]
iPhoneX Maxi, 13.5.1, in Safari, Tidio shown as expected and opened okay and fully readable.

**Comment by GeekOnCoffee** [comment]
Still seeing this in Chrome on Galaxy s20+

**Comment by brettski** [comment]
Get off you Galaxy then, sheesh
