### ISSUE TITLE
Animated Checkbox End-State

### ISSUE THREAD

**Issue by TheTopher** [ThatConference/that.us#157]
**Describe the bug**
When selecting one of the "Terms of Service" checkboxes, the box animates, but the end-state is not a checkmark.

**To Reproduce**
1. Go to 'Let's create THAT profile'
2. Click on any checkbox in the "Terms of Service" section
3. Watch the animation and notice the incorrect end-state

**Expected behavior**
A checkbox appearing in the box

**Screenshots**
<img width="528" alt="image" src="https://user-images.githubusercontent.com/6912293/88219214-e3268f00-cc26-11ea-994c-3ebf1cd1d6ab.png">

**Desktop (please complete the following information):**
 - OS: OSX 10.15.4
 - Browser Safari
 - Version 13.1

**Comment by brettski** [comment]
This seems to be Safari only. Good find. Not sure it will be fixed for the 3rd.

**Comment by brettski** [comment]
@all-contributors please add @TheTopher for bug

**Comment by csell5** [comment]
yea I'm not sure what to do here.. It's an svg with some animations on it. I'll file a bug over here and see if they know about it : https://github.com/HosseinShabani/svelte-checkbox/blob/master/Checkbox.svelte

**Comment by csell5** [comment]
filled issue https://github.com/HosseinShabani/svelte-checkbox/issues/2

**Comment by csell5** [comment]
they're working on a fix.
