### ISSUE TITLE
Stuck on My Session Submissions Page

### ISSUE THREAD

**Issue by TheTopher** [ThatConference/that.us#158]
**Describe the bug**
I went to "My Session Submissions Page" from the User-bug dropdown button and am stuck on the page with nothing to click.

**To Reproduce**
1. Click on User "bug"
2. Select "My Submissions"
3. See error

**Expected behavior**
See an empty "My Session Submissions" page with clickable items.

**Screenshots**
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/6912293/88220253-58469400-cc28-11ea-812e-6853e7f3018f.png">

**Desktop (please complete the following information):**
 - OS: OSX 10.15.4
 - Browser Safari
 - Version 13.1

**Additional context**
I completed my profile, but have not logged-out and back in.  Also, I don't have a profile picture.  Nor, do I have any submissions.

**Comment by brettski** [comment]
Do you have any submissions when this happened?

**Comment by TheTopher** [comment]
<img width="911" alt="image" src="https://user-images.githubusercontent.com/6912293/88221912-c1c7a200-cc2a-11ea-8932-6811d654aee2.png">

**Comment by TheTopher** [comment]
Here is more detail.
<img width="403" alt="image" src="https://user-images.githubusercontent.com/6912293/88222037-f76c8b00-cc2a-11ea-9e23-56380ef69e3a.png">

**Comment by TheTopher** [comment]
<img width="661" alt="image" src="https://user-images.githubusercontent.com/6912293/88222278-57fbc800-cc2b-11ea-8e16-f8b4aaa8a902.png">
