### ISSUE TITLE
Profile dropdown - Email address goes outside of predefined box

### ISSUE THREAD

**Issue by mcookWI** [ThatConference/that.us#168]
**Describe the bug**

When going to the profile dropdown menu at the top right of the screen, longer email addresses are not showing within the defined dropdown box.

**To Reproduce**

1. Click on the profile dropdown box on the top right corner of any page.
2. An longer email address goes outside of the defined dropdown box. See attached screenshot.

**Expected behavior**

The user's entire email address should show within the defined dropdown box. Is it possible to resize the text for longer email addresses, or make the defined dropdown box wider?

**Screenshots**

<img width="307" alt="Screen Shot 2020-07-22 at 8 05 21 PM" src="https://user-images.githubusercontent.com/5367626/88243975-c8b8d980-cc57-11ea-8e79-18d06ea77241.png">

**Desktop (please complete the following information):**
 
- OS: MacOS
 - Browser - Safari 13.0.5 / Chrome 84.0.4147.89

**Comment by brettski** [comment]
@all-contributors please add @mcookWI for bug,userTesting

**Comment by brettski** [comment]
@all-contributors please add @mcookWI for bug
