### ISSUE TITLE
Log In Status on Home Page is Unclear

### ISSUE THREAD

**Issue by MFazio23** [ThatConference/that.us#178]
**Is your feature request related to a problem? Please describe.**
When I go to the home page and am logged in, it doesn't tell me but it does remove the "Log In" buttons.

**Describe the solution you'd like**
Display some indication that the user's logged in, either the user's avatar in the top or switch the "Log In" link up top to the user's name.

**Describe alternatives you've considered**
Either the avatar or a name should work, but we just need to give people a heads up that they're signed in as expected.

**Additional context**
No log in buttons/links/indicators to be found
![Missing log in links/buttons](https://i.imgur.com/nFV5Z7N.png)

**Comment by zaudtke** [comment]
Closing as PR #181 has been merged.
