### ISSUE TITLE
Can't log into THAT lunch until I created my profile

### ISSUE THREAD

**Issue by jayerdahl** [ThatConference/that.us#184]
When going to https://that.us/join/that-launch-lunch, it launches a pop-up asking me to create my profile and I cannot click through that pop-up using either button.  Creating a profile resolved the issue, as there was no pop-up.

**To Reproduce**
1. Go to https://that.us/join/that-launch-lunch using Chrome on MacOS
2. Try to click either the "Create profile" button or other
3. Error is an inability to get past that pop-up

**Expected behavior**
The ability to NOT create a profile and still see that THAT Lunch

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.5
 - Browser: Chrome
 - Version: 83.0.4103.106 (Official Build) (64-bit)

**Comment by csell5** [comment]
@jayerdahl it is required to create a profile to attend a session. It doesn't have to be a public profile but we don't allow anonymous  users.
