### ISSUE TITLE
Session Times Missing 5:00PM and 5:30PM

### ISSUE THREAD

**Issue by TheTopher** [ThatConference/that.us#197]
**Describe the bug**
The times 5:00PM and 5:30PM are missing from the "Select time to chat" dropdown on the Session/Create and Sessions/Edit pages

**To Reproduce**
1. Create a new session
2. Click on the "Select time to chat" dropdown
3. Scroll down to where 5:00PM should be
4. See that it is missing

**Expected behavior**
Should be able to choose 5:00PM or 5:30OPM.
**Desktop (please complete the following information):**
 - OS: OSX 10.15.4
 - Browser Safari
 - Version 13.1

**Comment by csell5** [comment]
I pulled those times out for closing keynotes. Same with 8am.
