### ISSUE TITLE
Session Date/Time is Incorrect

### ISSUE THREAD

**Issue by MFazio23** [ThatConference/that.us#209]
**Describe the bug**
When loading a session, the session date/time is not always correct. Either it shows the correct date/time or a today's date with a time (seemingly) close to the current time.

**To Reproduce**
1. Go to https://that.us/sessions/8ZXlm7N2xhjvCMdRhdb6 (or any other session link)
2. View the session time and date
3. Session time/date _may_ be incorrect - refresh or open a new tab if not.

**Expected behavior**
The correct time/date should always show up.

**Screenshots**
![Incorrect session date/time](https://i.imgur.com/J0BNG7M.png)
(should be Aug 3 2020 - 04:00 pm)

**Desktop (please complete the following information):**
 - OS: Windows, Mac
 - Browser: Chrome (Win/Mac), Safari, etc.
 - Version: Whatever's installed on my laptops

**Additional context**
- Favoriting the session seems to "fix" the issue

**Comment by csell5** [comment]
LOL.. I left some testing code in.. who said don't test in production 🤔

**Comment by MFazio23** [comment]
You get way more testers this way!

**Comment by csell5** [comment]
@all-contributors please add @MFazio23 for bug
