### ISSUE TITLE
Login Button Navigates to Page Not Found

### ISSUE THREAD

**Issue by gemolle** [ThatConference/that.us#21]
![image](https://user-images.githubusercontent.com/60487024/87183316-87b1e400-c2ab-11ea-9744-7460dd8e5862.png)

1. Went to THAT.us
2. Clicked Login button to login
3. Takes you to Page not found

![image](https://user-images.githubusercontent.com/60487024/87183503-d9f30500-c2ab-11ea-89e5-d453e8fb075a.png)

**Comment by csell5** [comment]
The homepage isn't implemented yet.

**Comment by csell5** [comment]
depends on #39
