### ISSUE TITLE
Jitsi Window falling below outside of the default height.

### ISSUE THREAD

**Issue by csell5** [ThatConference/that.us#214]
**Describe the bug**

**To Reproduce**
1. Open in brave.
2. http://localhost:5000/join/3QR1EbLmqHPzYN7xJG2v

![image](https://user-images.githubusercontent.com/772569/88716208-58410b00-d0e4-11ea-86ce-994ee7d6092d.png)

**Expected behavior**
I thought we had it set to shrink?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: brave
 - Version 1.11.101 Chromium: 84.0.4147.89 (Official Build) (64-bit)

**Comment by saragibby** [comment]
Locally was in a join link/session that didn't have a title and "Session Details" button, those extra pixels are what is pushing it down too far. When frame is expanded do we want it covering the title and button?

**Comment by csell5** [comment]
Nice catch. Yea they're there for a proper session, whereas if we create an adhoc one I don't have that session information but yet I create a meeting room. Having said that, I should default that action bar with at least a solid default in that situation.
