### ISSUE TITLE
Dead Cancel Button for Create A New Chat 

### ISSUE THREAD

**Issue by gemolle** [ThatConference/that.us#22]
If choosing to cancel, rather than submit, a new chat idea, the Cancel button does not work. No action happens when clicking said cancel button.

![image](https://user-images.githubusercontent.com/60487024/87234495-14859c00-c397-11ea-93c8-9e4b1894ea5d.png)

**Comment by csell5** [comment]
Not implemented yet. Right now it just resets the form. Going to rename to reset for now.

**Comment by csell5** [comment]
Renamed button copy to `Reset`.
