### ISSUE TITLE
Always Display Join Button on Session Card

### ISSUE THREAD

**Issue by lukeplamann** [ThatConference/that.us#237]
It is unclear how to join a session because the join button does not appear until 5 minutes before the session starts. Maybe always show the join button, and enable it at T-minus 5 minutes. This would give a visual clue as to how the user will join the session when it is time.

Edit To Add: Keeping Favorites and Join buttons always visible will also help because at T-minus 5 minutes I can no longer see which sessions I made favorites. I don't like that.

**Comment by csell5** [comment]
@all-contributors will you please add @lukeplamann for issue

**Comment by csell5** [comment]
@all-contributors could you please add @lukeplamann for ideas
