### ISSUE TITLE
Avatar doesn't match on submitted session(s)

### ISSUE THREAD

**Issue by gemolle** [ThatConference/that.us#24]
After submitting session and returning to THAT Schedule, user avatar does not match with submitted sessions. Avatar will only match after getting THAT Schedule to refresh and reload. Specifically, screenshot is from when I submitted the 11:00am Test session. Both the 11:00am and 1pm sessions are my submitted test sessions. The 5:00pm session was submitted by Mike Cook; all others by Clark Sell. To get avatars to match, page had to be refreshed. Happened with both of my test sessions. It appears that the avatars are off by one session prior to refreshing page. 

To Recreate: 
* Log in using top navigation 
* Click on Create New Session
* Enter session info
* Click on Submit
* Upon automatic return to THAT Schedule, avatars do not match sessions
* Refresh page and avatars will be appear with correct sessions 

![image](https://user-images.githubusercontent.com/60487024/87235742-d7c0a180-c3a4-11ea-80c5-f631d7b15a64.png)

**Comment by csell5** [comment]
@gemolle can you try and retest?

**Comment by gemolle** [comment]
New test session created and avatars match without refreshing page

**Comment by brettski** [comment]
@all-contributors please add @gemolle for bug
