### ISSUE TITLE
OH NO appears after ending a session

### ISSUE THREAD

**Issue by kenssamson** [ThatConference/that.us#245]
After I disconnect from a session, I get 'OH NO' on the sessions page. Hitting refresh does reload the page correctly.

Console Log details....
```
sessions:1 Access to fetch at 'https://api.that.tech/' from origin 'https://that.us' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
api.that.tech/:1 Failed to load resource: net::ERR_FAILED
sessions.js:144 Uncaught (in promise) TypeError: Cannot read property 'events' of undefined
    at sessions.js:144
(anonymous) @ sessions.js:144
sessions.js:144 Uncaught (in promise) TypeError: Cannot read property 'events' of undefined
    at sessions.js:144
(anonymous) @ sessions.js:144
```

**Comment by brettski** [comment]
@kenssamson Does/did this happen after **every** time you exited a session, only once in a while, or only once? Will you please provide your OS name and version and Browser name and version.

How were you disconnecting, using the **red hang up button** or something else? a list of steps to reproduce would be helpful.

Thank you!

**Comment by csell5** [comment]
@all-contributors please add @kenssamson for bug

**Comment by csell5** [comment]
Actually this is happening because I'm doing a horrible job at error handling so if the api call fails.. that's my great handling ;)

**Comment by kenssamson** [comment]
How did this happen?

Occurred a few times after I hit the red phone icon to end a session. It may have happened more then I realized because after the first couple time, I started refreshing page instead of waiting for the error.

Setup:
Windows 10 - latest public build
Chrome - latest public build

**Comment by csell5** [comment]
resolved...
