### ISSUE TITLE
"Open in new tab" shortcut functionality

### ISSUE THREAD

**Issue by ps2goat** [ThatConference/that.us#253]
**Describe the bug**
I consider it a bug, but it may be a feature request. Middle mouse click seems to work to open a link in a new tab, but CTRL + Click does not. CTRL + Click is my default for opening a link in a new tab (e.g., when I want to view my schedule but I'm currently in a session!).

**To Reproduce**
1. Go anywhere on the site.
2. CTRL + click on a menu item (seems like all the links I click on)

**Expected behavior**
The destination should open in a new tab. Instead, my current tab is directed to the destination, making me exit the current session (or whatever else I may be doing).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 84.0.4147.105 (Official Build) (64-bit)

**Comment by csell5** [comment]
Great find. It currently has to do with how we're composing the component tree and trying to keep ya from going through the whole page cycle.. but yes. PITA, so we need to figure out how to support this.

**Comment by csell5** [comment]
@all-contributors please add @ps2goat for ideas

**Comment by csell5** [comment]
ref - https://github.com/pateketrueke/yrv/issues/57

**Comment by csell5** [comment]
```
function handle_click(e) {
  if (e.metaKey || e.ctrlKey || e.button !== 0) {
    // router should not handle this click
    return;
  }

  navigate(...);
}
```
