### ISSUE TITLE
Form Select a Day format

### ISSUE THREAD

**Issue by brettski** [ThatConference/that.us#267]
If we are going to use MM/DD/YYYY to display the day, then this needs to be added to the field description as many other countries use a different format, like UK who uses DD/MM/YYY. So perhaps do something like, **Select a Day (MM/DD/YYYY)**

Or perhaps what may look better in the field  is a log format: **Saturday, August 8, 2020** or **Saturday, Aug 8, 2020**, etc.

![image](https://user-images.githubusercontent.com/473633/89712020-b75c1680-d953-11ea-9ab4-330dfd722430.png)

**Comment by csell5** [comment]
are you talking in the button itself?

**Comment by brettski** [comment]
Added visual aid
