### ISSUE TITLE
Session create form errors if no Estimated duration is used

### ISSUE THREAD

**Issue by brettski** [ThatConference/that.us#268]
**Describe the bug**
When creating a new session if an Estimated Duration is not selected, the default is used, the form errors reading, "Please correct the errors listed above", though with no fields highlighted on why. 

**To Reproduce**
1. Go to create a new form
1. Add Title, description, time
1. DON'T touch Estimated Duration
1. Click submit
see error banner at bottom of screen

**Expected behavior**
The value 0:30 should be used and the form succeed. The field in error should be highlighted

**Screenshots**
![image](https://user-images.githubusercontent.com/473633/89711119-e079a880-d94d-11ea-9e20-8e6fc04ca634.png)

**Additional Notes**
Clicking on "Expected Duration** and keeping to 0:30 is enough to satisfy the value being set.

**Comment by csell5** [comment]
nice find.. and it's not showing the error in the form....

**Comment by csell5** [comment]
Fixed in PR
