### ISSUE TITLE
Disqus Login Form Failure

### ISSUE THREAD

**Issue by csell5** [ThatConference/that.us#29]
Try to login from the disqus plugin on a session detail.

![image](https://user-images.githubusercontent.com/772569/87317165-42302980-c4ec-11ea-8508-61ea03f2d8bb.png)

**Comment by csell5** [comment]
Can I get your help here. I'm guessing we have something messed up with our settings in disqus.

**Comment by brettski** [comment]
@csell5  I need steps to reproduce as I did not experience this when testing. 

By chance did you try to comment from your local dev environment? Disqus may not like the source domain, localhost...

**Comment by brettski** [comment]
https://that.us/sessions/ObtWJf1EkG3EgSZmSNYw

**Comment by csell5** [comment]
Looks like it was the brave shields that was blocking the disqus login from working.

**Comment by brettski** [comment]
@csell5 my brave shields are set default for that.us, fyi.

**Comment by csell5** [comment]
does that mean they're up?

**Comment by brettski** [comment]
affirmative

**Comment by csell5** [comment]
then I don't know what's going on here. other than it started to work when I took the shields down.
