### ISSUE TITLE
Sign in through certain OAuth providers pre-fills First+Last name with [object Object]

### ISSUE THREAD

**Issue by Ghosts** [ThatConference/that.us#297]
**Describe the bug**
When using GitHub & Apple (possibly others) as the OAuth sign-in providers, the Create Profile page is pre-filled with [object Object] for first + last name (seems to work as expected with Google).

**To Reproduce**
1. Click Log in
2. Choose GitHub / Apple / (possibly others)
3. Click on Create Profile under the user icon
4. Check First + Last name fields.

**Expected behavior**
First + Last name should be pre-filled with the user's information, or contain a placeholder if they were not provided by the OAuth provider. 

**Screenshots**
![Etg3YyK](https://user-images.githubusercontent.com/2401816/90837085-2fd8b500-e30e-11ea-8635-b6ab2ddf8f85.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 84.0.4147.135 

**Additional context**
Assuming that the format returned by the provider is either different across (naming, structure, etc.) or the data is simply not returned by Apple / GitHub, have not looked into the code yet for causes.

**Comment by brettski** [comment]
This will also happen on accounts setup using email/password. The reason that first and last name are not available is that they are not asked for. My guess with some providers, like GitHub, they are not getting name from the account, only email address.

**Comment by csell5** [comment]
The bug is here.

https://github.com/ThatConference/that.us/blob/master/src/routes/my/Profile.svelte#L27-L31

Right now we're assuming auth0 was returning a normalized set of data regardless of oauth provider and it's in fact not. For example, github will only return name as 'clark sell' and the $user object doesn't contain a givenName or familyName.
