### ISSUE TITLE
Wider screen sizes make it difficult to click footer links on changelog page

### ISSUE THREAD

**Issue by brettski** [ThatConference/that.us#353]
PR #349 
**Describe the bug**
When the site is is at wider widths on the `/changelog` page the top row of links in the footer are covered by a div making them difficult to click. 

**To Reproduce**
at any non-narrow page width
1. Go to `/changelog`
1. Go to the page's footer and try to click on any of the top row links.
1. only the bottom of the link is active

**Expected behavior**
The entire word should work as a link as it does on the other pages in the site. 

**Screenshots**
![image](https://user-images.githubusercontent.com/473633/93802842-9997f780-fc09-11ea-95d5-b9b810455739.png)

**Desktop (please complete the following information):**
Screens around 1100px or wider. I didn't look for the collapse points. 

**Smartphone (please complete the following information):**
- not tested

**Comment by csell5** [comment]
yea, that's a problem...

**Comment by brettski** [comment]
Looks good, I'll let the PR close this
