### ISSUE TITLE
Implement Favorites

### ISSUE THREAD

**Issue by csell5** [ThatConference/that.us#38]
Implement the call to favorite a session for a given user.

**Comment by brettski** [comment]
@csell5 is the expectation that the "favorite ❤️ " button show as favorited for a logged in user, when they have that session favorited?

**Comment by brettski** [comment]
Get the favorite sessions for a member for an event. returns all favorited sessions
```graphql
query memberFavorites ($eventId: ID!) {
  sessions {
    me {
      favorites(eventId: $eventId) {
        id
      }
    }
  }
}
```

toggle favorite session for member:
If session is now favorited toggle returns **AcceptedSession** type.
if session is now NOT favorited the toggle returns **null**.
```graphql
mutation toggleFavorite($eventId: ID!, $sessionId: ID!) {
  sessions {
    favoriting(eventId: $eventId) {
      toggle(sessionId: $sessionId) {
        id
      }
    }  
  }
}
```
