### ISSUE TITLE
NavBar is getting cut off on smaller breakpoints (mobile) 

### ISSUE THREAD

**Issue by csell5** [ThatConference/that.us#384]
The nav bar is getting cut off on the iPad and it appears the background is just too smaller on the smaller breakpoints.

**To Reproduce**
1. Go to https://that.us on an iPad
2. Look at the nav bar.

**Expected behavior**

The header is getting cutoff on the bottom. It should match what you see on a desktop.

**Screenshots**
![image](https://user-images.githubusercontent.com/772569/94876038-1d2cc200-041c-11eb-8aa0-d687eae767f4.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Safari

**Additional context**
It appears the smaller breakpoints don't have a big enough background to cover the new size of the headroom header.

**Comment by thalesagapito** [comment]
I could help out with this!

**Comment by csell5** [comment]
@thalesagapito that's awesome, thanks. It should be pretty straight forward but if you need help ping me and we can setup something.
