### ISSUE TITLE
feature request: Add Sign-up to user menu

### ISSUE THREAD

**Issue by brettski** [ThatConference/that.us#386]
**Is your feature request related to a problem? Please describe.**
When not logged in the menu below the user icon has `Login` option. My suggestion is to also add a `Sign-up` link to the menu as well. 

**Describe the solution you'd like**
Add sign-up option to not authenticated user menu

**Additional context**
![image](https://user-images.githubusercontent.com/473633/94970581-95ea5780-04ca-11eb-8a49-ff69ba4dd3fa.png)

**Comment by ReazerDev** [comment]
Hi, I got it ready, but I have no permissions to push my branch :)

**Comment by brettski** [comment]
Hi @ReazerDev Create PR from your fork to this repo.

**Comment by ReazerDev** [comment]
Opened a PR

**Comment by brettski** [comment]
allcontributors please add @ReazerDev for code

**Comment by brettski** [comment]
@all-contributors please add @ReazerDev for code
