### ISSUE TITLE
Lifehack should be optional

### ISSUE THREAD

**Issue by GeekOnCoffee** [ThatConference/that.us#413]
**Describe the bug**
lifeHack must be a `string` type, but the final value was: `null`. If "null" is intended as an empty value be sure to mark the schema as `.nullable()`

**To Reproduce**

Edit Profile
Dont fill in Livehack
Submit
See Error

**Expected behavior**
Edit Profile
Dont fill in Livehack
Submit
Profit

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by csell5** [comment]
it is actually. checkout #407 #408 Clearly that didn't fix it.
