### ISSUE TITLE
New profile gets [object Object] for names

### ISSUE THREAD

**Issue by coreyhaines** [ThatConference/that.us#453]
**Describe the bug**
After signing up with email and password, then going to create the profile, see '[object Object]' for the name fields.
![image](https://user-images.githubusercontent.com/3962/97591515-b1635800-19cd-11eb-8440-f79dc073098b.png)

**To Reproduce**
1. Sign up with new email/password
2. Go to user profile
3. Bask in the javascript goodness

**Expected behavior**
Should be blank

**Screenshots**
![image](https://user-images.githubusercontent.com/3962/97591630-cf30bd00-19cd-11eb-99f8-0f58ddfb404f.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Laptop
 - OS: OSX
 - Browser Brave
 - Version 1.15.76, chromium 86

**Comment by csell5** [comment]
@all-contributors please add @coreyhaines for bug

**Comment by csell5** [comment]
duplicate of #297
