### ISSUE TITLE
Typo in FAQ

### ISSUE THREAD

**Issue by sojan80** [ThatConference/that.us#482]
There is a typo in the response for "I have a cool idea for THAT.us, where can I submit it.

Shouldn’t that read ‘located at’ or located on’, or even just more simply, ‘on’,
As in “That.us is a fully open source project located at GitHub…” or “That.us is a fully open source project located on GitHub…” or “That.us is a fully open source project on GitHub…”
![FAQTypo](https://user-images.githubusercontent.com/13117568/98420198-45779400-204c-11eb-8124-b634427d0e23.GIF)

**Comment by csell5** [comment]
@all-contributors please add @sojan80 for bug.
