### ISSUE TITLE
filter by communities in the activity filter slide out

### ISSUE THREAD

**Issue by csell5** [ThatConference/that.us#514]

**Comment by asharonbaltazar** [comment]
Are the communities included in the activity data?

**Comment by csell5** [comment]
a community is defined by having an @ in the `title`, `description` or `tags`. the way search is now, you should be able to just type @[whatever] and it pull up. What it's not is clear that you can do that. 

It would be great to just add another section like the tags, that pulls in any @[community] just so it's a bit more explicit.

Does that make sense? 

![image](https://user-images.githubusercontent.com/772569/106023551-82bc5280-608c-11eb-8ed5-4f0ce8368c7b.png)

**Comment by asharonbaltazar** [comment]
Yes, it makes sense. So are these communities listed somewhere? Because if they are, you can also add suggestions while typing in the search box.

**Comment by csell5** [comment]
sorta kinda not really. I'm not sure we have all of the api work done to do that, but right now the activities page is setup to be a paged page. Now mind you I haven't finished that conversion, like I have on the other pages such as https://that.us/members

I say that because, search right now is based on what's been already queried. so if you were at the start of the page ( say 50 records ) then you filter down that result vs calling the API and fetching a new result set then paging that.

We took that direction for now as more of baby steps until we have an opportunity to put some more headspace around how to best search, filter, follow.

**Comment by asharonbaltazar** [comment]
Okay, seems simple enough. I don't know what you're thoughts on `reduce` are, but we can push tags into one array and communities into another. So cybersecurity is the only community listed in the tags?

**Comment by csell5** [comment]
If there was a community section as a peer to tags, it seems redundant to have those values also listed in tags.

**Comment by asharonbaltazar** [comment]
I'm thinking of having an `if` checking whether the tag begins with @ and then put it in a separate `div`. That would mean some fancy rearranging of the `div` holding "Tags" and the "Clear selected tags" button or changing the layout completely. However, unfamiliar as I am with Svelte, I'm not sure how to do that. Personally, I would have the array filtered upon render(?) and then map them to their respective places.

**Comment by csell5** [comment]
so, couple things.

* Actually it looks like we keep an array of communities on the AcceptedSession https://api.that.tech/view look for the type AcceptedSession.
* Given that, We just need to add that to our query.

**Comment by asharonbaltazar** [comment]
Should I open an issue for this?

![image](https://user-images.githubusercontent.com/58940073/106176827-6805de80-615d-11eb-8c4d-9cd024c9cba1.png)

**Comment by csell5** [comment]
meaning if there are no results it all just collapses to nothing and looks like hell? if yes, then yea, we should create an issue and just show no results found type of thing.

**Comment by asharonbaltazar** [comment]
I hope your crash reports are disabled on development builds... 😁

**Comment by csell5** [comment]
nope, but it was intentional. We can filter them out, or provide more details if need be.

**Comment by asharonbaltazar** [comment]
Okay, I'm slowly taking baby steps towards displaying communities in the filter slideout. I'm not familiar with Svelte, but I'm doing a hybrid of copy/paste and my own work as I go along.

**Comment by csell5** [comment]
Happy to help if you have questions. you can always join us in slack and hit me up.

**Comment by asharonbaltazar** [comment]
Would you want the communities filtered from tags now?

**Comment by csell5** [comment]
Yea I would. as it would be redundant and a bit confusing.

**Comment by asharonbaltazar** [comment]
So there's really no reason to have a separate query for communities. They're already marked with @, so it'd be easy to filter them out and push them to a separate array. As evident from the photo below:

![image](https://user-images.githubusercontent.com/58940073/106205584-54ba3980-6184-11eb-972c-b312ff591863.png)

To get those communities, I've added a parameter(?) in the `sessions.js` file:
![image](https://user-images.githubusercontent.com/58940073/106205665-787d7f80-6184-11eb-927f-e1bf6b4b426e.png)

What're your thoughts?

**Comment by csell5** [comment]
exactly, right on. I'd only filter out on that slide out display too, as we would still want to see them on the cards in the list.

and by adding communities, you've got all the data you'd need in one place.

**Comment by asharonbaltazar** [comment]
Only one problem: the `"@madison-geek-lunch"` seems to be a community but `@"@madison-geek-lunch robotics coding security tech"` isn't. Which is it?

**Comment by csell5** [comment]
that's a data problem. So they added a tag, but didn't hit enter as the delimiter so now there is one very long tag. We should log an issue to add some validation that a tag which has @ in it, should have any spaces. For now we will manually fix up this data.

**Comment by asharonbaltazar** [comment]
Okay, it's basically finished. I'll drop a PR right now. However, something needs to be done about That. Either it's a community or a tag...

**Comment by csell5** [comment]
fixing it now..
