### ISSUE TITLE
Would like to start meetings on the quarter hour

### ISSUE THREAD

**Issue by eselje** [ThatConference/that.us#516]
**Is your feature request related to a problem? Please describe.**
Activity starts at 11:45am and goes until 1:00pm

**Describe the solution you'd like**
For me, 15m discretion is good but maybe others would like it even more discrete

**Describe alternatives you've considered**
Start at 11:30am (not ideal)

**Additional context**
I got nothing

**Comment by csell5** [comment]
@all-contributors please add @eselje for bug
