### ISSUE TITLE
Odd Hanging Date overlap on Activities page

### ISSUE THREAD

**Issue by sojan80** [ThatConference/that.us#531]
I was scrolling down the activites page when I noticed the Tuesday November 24 date banner was still at the top of the page as and everything else was scrolling below it. Then when I hit Wednesday Novermber 25 the first Date Time heading for that took it's place and so on as you scroll down the page.
![Activities Date Banner Issue](https://user-images.githubusercontent.com/13117568/100107830-b3cf9b00-2e2f-11eb-9f06-814bcbb11b49.GIF)

**Comment by csell5** [comment]
Verified session in logrocket. Currently working as designed.

It would be a nicer UX if the date was pushed out of the way with the last card, but right now it's being pushed out of the way with the next date.

**Comment by asharonbaltazar** [comment]
I'll have a go at this, please. Seems to be an easy styling fix.
