### ISSUE TITLE
Partner cards don't animate like member or communities do

### ISSUE THREAD

**Issue by brettski** [ThatConference/that.us#534]
**Describe the bug**
Partner cards don't animate like member or communities do

**To Reproduce**
1. Go to communities, hover over any community and see how it animates on hover
1. Go to members, hover over any member and see how it animates on hover
1. Go to partners, hover over any partner and notice that there is no animation.

**Expected behavior**
Experience on partner page should be consistent with the others

**Comment by asharonbaltazar** [comment]
I'll take this, please

**Comment by brettski** [comment]
> I'll take this, please

Thank you @asharonbaltazar! Much appreciated.

**Comment by asharonbaltazar** [comment]
PR incoming...
