### ISSUE TITLE
Cannot see fields when creating an activity

### ISSUE THREAD

**Issue by mmillican** [ThatConference/that.us#541]
**Describe the bug**
Using Firefox on Windows, I cannot see the actual inputs for the first two fields on https://that.us/activities/create (see screenshot)

**To Reproduce**
1. Go to https://that.us/activities/create
2. Look for inputs on the "What would you like to chat about?" and "Explain a bit more..." fields

**Expected behavior**
I would expect to see input borders to indicate where the actual inputs are

**Screenshots**
![image](https://user-images.githubusercontent.com/810260/102366726-9a2cf980-3f7e-11eb-81e7-33e8f3b4b588.png) (note that the icon at the right of the "What..." field is LastPass.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 83.0

**Comment by csell5** [comment]
@mmillican when you say see you mean 👀 on the border correct? As in.. It's there, but hard to visually see.

**Comment by mmillican** [comment]
@csell5 Yep - I suppose that's correct - I honestly had to look again super closely to see it.

**Comment by csell5** [comment]
just making sure. Should be an easy fix.

**Comment by csell5** [comment]
@all-contributors please add @mmillican for bug
