### ISSUE TITLE
Long titles mess up community cards on grid.

### ISSUE THREAD

**Issue by csell5** [ThatConference/that.us#543]
![image](https://user-images.githubusercontent.com/772569/103583311-2444ef80-4ea5-11eb-8fa8-4c6155298cdc.png)

**Comment by asharonbaltazar** [comment]
Hey, I'd like to take a shot at this. What would you like the final output to look like?

**Comment by csell5** [comment]
@asharonbaltazar that would be awesome. I must be shrinking but essentially the height should just fill to whatever the longest is. so where the pink boxes are, it should just extend down. If you look on the past activities page the grid does it there https://that.us/events/thatUs find a slot that has multiple and then just resize the window. I make up for the extra space in the tags.

For this page. I think just aligning the activities and followers to the bottom and leaving the space between the title and that would be more than fine. Down the road we will change that data, as it's a bit confusing. 

Does that make sense?

**Comment by asharonbaltazar** [comment]
Yes, but in the case of LA CROSSE AREA SOFTWARE DEVELOPERS, I don't think this solution would work, right?

**Comment by csell5** [comment]
it just wouldn't have any space as it would be the item setting the height for the others.

**Comment by asharonbaltazar** [comment]
In the `CommunityCard`, do you want this set as `bold` or `semibold`?

![image](https://user-images.githubusercontent.com/58940073/105744283-7efcc480-5f02-11eb-99e7-a00b6ff103c3.png)

**Comment by csell5** [comment]
🤦 LOL.. bold. remove font-semibold
