### ISSUE TITLE
process.env for that.us

### ISSUE THREAD

**Issue by csell5** [ThatConference/that.us#550]
For now I think we really only need the following three. The other keys are all in the config, but they're really all static stuff right now.

* process.env.NODE_ENV
* process.env.STRIPE_KEY
* process.env.XSTATE_DEBUG - should be set to false in all env.

**Comment by csell5** [comment]
@brettski updated with the keys

**Comment by brettski** [comment]
@csell5  For `NODE_ENV` which value would you like set for the `preview` environment?

**Comment by brettski** [comment]
`STRIPE_KEY` is setup for `production` and `preview` secrets. The `production` key is our Stripe `live mode` key. Which means that the price ID's currently on products will not match to to Stripe product price id's.

`XSTATE_DEBUG` is setup in all evironments

`NODE_VER` is setup in `production` and `development`, a value is needed for the `preview` environment.

**Comment by csell5** [comment]
does vercel set it to `preview`? if not that's a pretty good descriptor.

**Comment by brettski** [comment]
From what I have found Vercel doesn't set, `NODE_VER` at all. I will add that to the settings.

**Comment by brettski** [comment]
@csell5 The settings are complete. They can be found [here](https://vercel.com/that-conference/that.us/settings/environment-variables).

The values for `NODE_ENV` are lower case.

**Comment by csell5** [comment]
This is should be all good to go. https://github.com/ThatConference/that.us/blob/cs/feature/rollup.config.js#L53-L59
