### ISSUE TITLE
Need helper text when filter search produces no results

### ISSUE THREAD

**Issue by asharonbaltazar** [ThatConference/that.us#562]
**Describe the bug**
Nothing is notifying the user — other than an empty white `div` — that their query for a certain keyword has produced anything

**To Reproduce**
1. Go to Activities
2. Click on the filter button in the right corner
3. Type some text that doesn't produce results (e.g. rainbows 🌈)
4. User is presented with an empty white `div`, basically leaving the UX unfinished. 

**Expected behavior**
Something along the lines of "Oops, we didn't find anything" or "No such query exists." 

**Screenshots**
![image](https://user-images.githubusercontent.com/58940073/106176827-6805de80-615d-11eb-8c4d-9cd024c9cba1.png)

**Comment by csell5** [comment]
@asharonbaltazar do you want this one?

**Comment by asharonbaltazar** [comment]
I'll take it. Hopefully, the other ones will be finished soon.
