### ISSUE TITLE
Dates are squished in /activities, and the filter needs to rearranged

### ISSUE THREAD

**Issue by asharonbaltazar** [ThatConference/that.us#565]
**Describe the bug**
Due to the large font size, the dates appear squished on the that.us/activities. The filter input is hidden behind the dates too. 

**To Reproduce**
1. Go to that.us/activities
2. Turn on dev tools and simulate a mobile browser
3. See the lack of responsiveness. 

**Expected behavior**
It should look normal, just like on a larger display. 

**Screenshots**
![image](https://user-images.githubusercontent.com/58940073/106487322-28e6ce80-6478-11eb-9546-9550a3c15e10.png)

**Comment by asharonbaltazar** [comment]
@csell5 I'll take this one.

**Comment by asharonbaltazar** [comment]
Is there anything I can do about the chat bubble? It would literally solve all woes if its `z-index` was upped just slightly.

**Comment by csell5** [comment]
Can you explain more? What is it messing with? We could change it, but right now it's set to be under the notifications that appear at the bottom of the site.

**Comment by asharonbaltazar** [comment]
The chat bubble `z-index` causes it to appear underneath the titles in the Activities page. Is it possible to somehow increase it?

**Comment by csell5** [comment]
Gotcha.. yea it's set in app. https://github.com/ThatConference/that.us/blob/master/src/App.svelte#L39 we just need to make sure it's under those notifications.
