### ISSUE TITLE
Editing Button Arrangement Is Confusing

### ISSUE THREAD

**Issue by TheTopher** [ThatConference/that.us#608]
**Describe the bug**
The buttons for the editing are confusing.  The current arrangement is as follows
* "Update"
* "Cancel/Withdraw"

The "Update" button is next to a button with the word "Cancel/Withdraw".   Pressing the "Cancel/Withdaw" deletes the event.  

Ideally, these should be three buttons.
* "Update" - Save the edits and go to the event list.
* "Cancel" - Cancel the edits and go to the event list.
* "Withdraw" (although "Delete" might be better) - Delete the event and go to the event list.

OR, less than ideally
* remove the word "Cancel" from the button.

**To Reproduce**
1. Go to an events
2. Click on Edit
3. See the buttons at the bottom

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Safari (13.1.3)
 - Version 10.15.7

**Comment by csell5** [comment]
@TheTopher how are you with the new layout? Any thoughts?

**Comment by TheTopher** [comment]
I love it!  It’s looking great.  Just finished my morning meetings.  Going to go through the site.

Christopher Ebbert
***@***.***
612.701.7701


From: Clark Sell ***@***.***>
Reply-To: "ThatConference/that.us" ***@***.***>
Date: Wednesday, March 24, 2021 at 10:26 AM
To: "ThatConference/that.us" ***@***.***>
Cc: Christopher Ebbert ***@***.***>, Mention ***@***.***>
Subject: Re: [ThatConference/that.us] Editing Button Arrangement Is Confusing (#608)


@TheTopher<https://github.com/TheTopher> how are you with the new layout? Any thoughts?
