### ISSUE TITLE
"View Your Past Submissions" Button Text is Difficult to See

### ISSUE THREAD

**Issue by TheTopher** [ThatConference/that.us#622]
**Describe the bug**
The "View Your Past Submissions" on the ~/activites/edit page is difficult to read due to the colors.

**To Reproduce**
1. Go to any ~/activites/edit
2. Look for the "View Your Past Submissions" button

**Expected behavior**
More contrast

**Screenshots**
![image](https://user-images.githubusercontent.com/6912293/112352977-4296dc00-8c99-11eb-9048-14576d8261df.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Safari V13.1.3
 - Version 10.15.7

**Comment by csell5** [comment]
ref: #609
