### ISSUE TITLE
PM Time Options Not Available

### ISSUE THREAD

**Issue by TheTopher** [ThatConference/that.us#623]
**Describe the bug**
While trying to create an event for "THAT Online April", there were no times in PM in the dropdown.

**To Reproduce**
1. Create a new activity
2. Choose "THAT Online - April"
3. Select "Friday Apr 16, 2021"
4. Open "Starting Time" dropdown and notice only AM times.

**Expected behavior**
PM times available for selection

**Screenshots**
![image](https://user-images.githubusercontent.com/6912293/112353990-45de9780-8c9a-11eb-9894-301632fa08fb.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Sarfari V13.1.3
 - Version: 10.15.7

**Comment by csell5** [comment]
Actually that is correct. The event ends 24hrs after it started. Having said that... We need to make it more clear that's how were going to run it.

**Comment by TheTopher** [comment]
Understood
