### ISSUE TITLE
My Favorites Page Crashes

### ISSUE THREAD

**Issue by TheTopher** [ThatConference/that.us#642]
**Describe the bug**
I tried to go to "My Favorites" and saw the message (below).  I try to refresh the page but it constantly appears.

**To Reproduce**
1. Go to My Favorites by the upper-right face icon.
2. See the error message

**Expected behavior**
Should be able to see My Favorites page

**Screenshots**
![image](https://user-images.githubusercontent.com/6912293/112700265-c13b7700-8e5b-11eb-976b-b65410b6cb2b.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.15.7
 - Browser Safari 13.1.3

**Comment by csell5** [comment]
Do you know if you have any favorites?
