### ISSUE TITLE
Upcomming Events & Activities

### ISSUE THREAD

**Issue by rolandolopez** [ThatConference/that.us#665]
**Describe the bug**
The two buttons on the main page after logging in that are calling for Upcoming Events and Activities is misspelled 

**To Reproduce**
1. Go to that.us
2. log in
3. see the error

**Screenshots**
![Screen Shot 2021-03-31 at 12 29 37 PM](https://user-images.githubusercontent.com/1054389/113186108-dd089980-921c-11eb-9937-01e80072a30e.png)

**Comment by zo0o0ot** [comment]
I came to put in this ticket, as well.
https://github.com/ThatConference/that.us/search?q=upcomming

I think it's in: src/components/home/Hero.svelte

**Comment by zo0o0ot** [comment]
Looks like there's a PR in #664

**Comment by csell5** [comment]
@walesmd fixed it for us 🥳
