### ISSUE TITLE
Paid for annual membership, but cannot create an activity for 4/15 or 5/15 THAT events.

### ISSUE THREAD

**Issue by zo0o0ot** [ThatConference/that.us#667]
**Describe the bug**
I paid for an annual membership, and wanted to make an activity, I couldn't, even though I paid for an annual membership.

**To Reproduce**
1. Order an annual membership.
2. Fill out and complete profile. Save it.
3. Click "Activities" tab.
4. Click "Create Activity" button.
5. Daily That is OK,  THAT Online - April and THAT Online  - May are disabled.
6. Clicking the event brings me to the event page, which suggests I buy a monthly ticket.

**Expected behavior**
I expected to be able to create an event after purchasing the annual membership. Order iMGcIh6sBKtTAsPEWwaT shows up in my order history.

**Screenshots**
![image](https://user-images.githubusercontent.com/876146/113201919-bbfd7400-922f-11eb-960e-b8cb90c5b4f3.png)

**Desktop (please complete the following information):**

- OS: [Win 10]
- Browser [Chrome]
- Version [Version 89.0.4389.90 (Official Build) (64-bit)]

**Additional context**
FYI, I decided to make a Daily THAT, and I did it on 4/15 at 2PM, and nothing stopped me from signing up, event though it was a ticketed THAT day.  It looks like one place should be opened up, and another place should be tightened up.
Thanks for everything you do. I'm patient as you iron out the bumps.

**Comment by csell5** [comment]
@zo0o0ot so right now that landing page doesn't hide the purchase options.. feature to come #668

**Comment by csell5** [comment]
Query is for some reason returning false.
![image](https://user-images.githubusercontent.com/772569/113207466-43e67c80-9236-11eb-9bc6-15be50aad0a1.png)

CorrelationId - db0a55da-e7b1-4551-9226-d355cd89c6ed

**Comment by csell5** [comment]
Needs to also include UI changes.
