### ISSUE TITLE
Undefined field in Tidio Chat bot 

### ISSUE THREAD

**Issue by tsidel** [ThatConference/that.us#710]
**Describe the bug**
On https://www.that.us, I opened the Chat bot in the lower right corner of the screen. Typed my question, it then asked me to introduce myself and presented me with two fields... an email address field, and the second field has "undefined undefined" in it.

**To Reproduce**
1. Go to that.us
2. Click on the chat logo in the lower right
3. Entered a message
4. Clicked the "airplane" (send) icon
4. On the next screen fill out email field, see "undefined undefined" field
5. Hit send
6. Chat starts, everything does work as expected, and I'm able to communicate with the chatbot.

**Expected behavior**
The unexpected field "undefined undefined" lead a user to believe this may not work or something was done wrong

**Screenshots**
![image](https://user-images.githubusercontent.com/194128/117512516-65353980-af55-11eb-82f3-a622c0b970c4.png)

**Desktop (please complete the following information):**
 - OS: Mac BigSur 11.2.3
 - Browser: Chrome 90.0.4 & Firefox 88

**Comment by csell5** [comment]
fixed with #810
