### ISSUE TITLE
Editing Activity - Doesn't Display the Time Set

### ISSUE THREAD

**Issue by TheTopher** [ThatConference/that.us#722]
**Describe the bug**
When going in to edit and activity, the time is missing

**To Reproduce**
1. Create an activity
2. Edit the activity
3. Notice that the time selected is missing

**Expected behavior**
The time should be set 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser chrome

**Comment by csell5** [comment]
did you happen to change the event?

**Comment by TheTopher** [comment]
I may have.  Let me check again.

**Comment by TheTopher** [comment]
Yes, I did.

**Comment by csell5** [comment]
intentional then. I'm assuming because you changed the event the time is no longer valid.
