### ISSUE TITLE
og:image Points to the wrong image location

### ISSUE THREAD

**Issue by joshpierce** [ThatConference/that.us#752]
**Describe the bug**
Currently the og:image meta tag is pointing to https://that.us/images/favicon.png when the favicon currently lives at https://that.us/favicon.png. This prevents link unfurling from showing a graphic when sharing that.us links across the web.

**To Reproduce**
1. Navigate to https://www.opengraph.xyz/url/https:%2F%2Fthat.us/
2. See that there isn't an image associated with the unfurled link.

**Expected behavior**
Unfurled links should include the favicon.

**Screenshots**
![image](https://user-images.githubusercontent.com/8643537/122134476-49e70500-ce04-11eb-95c1-57537eb82d17.png)

**Comment by joshpierce** [comment]
After looking at what's available, there are a number of favicons / og images, so not sure what you want this pointed to.

### Existing FavIcon Render 
![image](https://user-images.githubusercontent.com/8643537/122143636-6f313e80-ce17-11eb-9223-632bfe659c85.png)

### THAT Trees Render
![image](https://user-images.githubusercontent.com/8643537/122143664-7d7f5a80-ce17-11eb-8209-d7fd68445b42.png)

### THAT Square Blue (Concept)
![image](https://user-images.githubusercontent.com/8643537/122143683-8a03b300-ce17-11eb-89d8-8e25fb66be69.png)

Does one of these speak to you? Do you have a specific image in mind for the og:image?

**Comment by csell5** [comment]
I reshuffled a few things around a while back. it should just be `/favicon.png` in the root not `/images/favicon.png`.

**Comment by csell5** [comment]
aka the red tree.
