### ISSUE TITLE
Clone Activity

### ISSUE THREAD

**Issue by csell5** [ThatConference/that.us#755]
**Is your feature request related to a problem? Please describe.**
A user should be able to easily clone an existing activity.

**Describe the solution you'd like**
If an activity has passed, a user should see two options `edit` and `clone` as two options in /my/submissions. Edit wouldn't allow them to change the event but rather tweak it, where clone would create a new activity pre-populated from that ole activity.

**Additional context**
Just take that activity and pre-populate the form

**Comment by asharonbaltazar** [comment]
Hey, I'll take a shot at this. Seems interesting

**Comment by csell5** [comment]
@asharonbaltazar all yours. this should be pretty straight forward but if you have any questions, let me know.

**Comment by csell5** [comment]
implemented.
