### ISSUE TITLE
Upgrade to use Svelte Kit

### ISSUE THREAD

**Issue by joshpierce** [ThatConference/that.us#765]
**Describe the solution you'd like**
Would like to upgrade the codebase to run on [Svelte Kit](https://kit.svelte.dev/), the path forward for SSR and Static Generation of Svelte apps.

**Additional context**
One of the big reasons to upgrade would be the better support of HMR with vite for a more efficient developer experience, including almost instantaneous generation of custom css via tailwindcss. 

_Note:_ As of this comment, TWCSS 2.2.2 JIT mode has [issues](https://github.com/tailwindlabs/tailwindcss/issues/4683) with vite, but I believe those will be resolved in the next release, short term workaround [here](https://github.com/tailwindlabs/tailwindcss/issues/4683#issuecomment-864441548).

**Comment by csell5** [comment]
holding until after WI '21

**Comment by csell5** [comment]
YO YO WE DID IT!
