### ISSUE TITLE
Users should be able to see extended details about a session on that.us to make the schedule more useful.

### ISSUE THREAD

**Issue by joshpierce** [ThatConference/that.us#773]
**Describe the solution you'd like**
We need to include things like the takeaways and assets in the session details on that.us.

**Considerations**
Should the site provide things like assets to users that haven't purchased a ticket for the event, thus wouldn't be in attendance?

**Comment by csell5** [comment]
I think it's ok to list those things regardless. Those users have missed the session and the conversation around it and we want to pass along as much google juice to others that we can.
