### ISSUE TITLE
callout about timezones in the users timezone.

### ISSUE THREAD

**Issue by csell5** [ThatConference/that.us#781]
**Describe the bug**
once upon a time we used to denote that the times were shown in the user's timezone. that's now missing or managed to get removed.

**Expected behavior**
Somewhere don't the activity list, note that the timezones are displayed in the users timezone.

**Comment by SQrL143** [comment]
Please assign this to me.

**Comment by SQrL143** [comment]
@csell5 I created PR #826 to resolve this issue. Please review.

**Comment by SQrL143** [comment]
PR #826 addressed this on computers, not mobile
