### ISSUE TITLE
load next threshold too small

### ISSUE THREAD

**Issue by csell5** [ThatConference/that.us#782]
**Describe the bug**
Right now you have to scroll too far ( like closer to the footer ) to get the next page to come in on activities. I think this is now coming in because of the sponsors component and being taller.

**To Reproduce**
scroll down /activities when you have to scroll into the footer to get the next to load but then you have to scroll back up to even know data was loaded as you've now passed the loading animation.

**Expected behavior**
I think we just n

**Additional context**
Not sure how this will affect things on mobile or tiny screens.

**Comment by csell5** [comment]
@asharonbaltazar can you take a look into this one?

**Comment by asharonbaltazar** [comment]
👀

**Comment by RunDLL32-Steve** [comment]
Did not see any assignees, so submitted PR

**Comment by asharonbaltazar** [comment]
@RunDLL32-Steve 
Did you see this conversation first?

**Comment by RunDLL32-Steve** [comment]
@asharonbaltazar I did not, otherwise I would not have submitted a PR.

**Comment by csell5** [comment]
It's my bad, I should have assigned this asap when @asharonbaltazar commented. Sorry about that.

**Comment by asharonbaltazar** [comment]
Your site should have more issues so there's a lot more to go around 😆

**Comment by csell5** [comment]
or better said.. I need to get better at loading the stuff in here.
