### ISSUE TITLE
Selected event speakers need to be displayed differently

### ISSUE THREAD

**Issue by csell5** [ThatConference/that.us#783]
**Is your feature request related to a problem? Please describe.**
Currently, all sessions show the same on the schedule. We need visually highlight the sessions that we've picked vs the ones that were added. Mind you these two types of sessions are different. Speakers picked from our CFP are a session type of regular whereas those added later are open spaces, so the data is there, it's just a matter of figuring out the UX/UI

**Comment by asharonbaltazar** [comment]
Where can I find these sessions?

**Comment by asharonbaltazar** [comment]
Ah, do you have anything that I can do?
