### ISSUE TITLE
Styling bugs on account area with mobile menu.

### ISSUE THREAD

**Issue by blitzmann** [ThatConference/that.us#784]
**Describe the bug**
Login / account area in menu on mobile looks a little janky

**To Reproduce**
1. Use mobile resolution
2. Go to https://that.us/activities
3. Click on Hamburger menu

When logged in:
Weird border on the bottom
Avatar is just kind of floating there. I would expect the avatar to float to the left of the name and email (at least I think it would look nicer)

When not logged in:
The colors for the login / signup are very slightly different than the other menu text
The user icon is lonely. Maybe just... get rid of it if not logged in? 

**Screenshots**
![image](https://user-images.githubusercontent.com/3904767/123458423-0aae7600-d5b3-11eb-9e77-1a885be502eb.png)

![image](https://user-images.githubusercontent.com/3904767/123459064-ca9bc300-d5b3-11eb-834e-f321f5918bc4.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 91

**Comment by csell5** [comment]
@all-contributors please add @blitzmann for bug.
