### ISSUE TITLE
Mark the required fields on the Profile form

### ISSUE THREAD

**Issue by csell5** [ThatConference/that.us#794]
**Is your feature request related to a problem? Please describe.**

On the profile form, add a small red dot next to each of the Form Labels for the fields that are required. This was done on the Create Activity form as seen here.  

![image](https://user-images.githubusercontent.com/772569/123864524-7b75cb00-d8f0-11eb-96c3-fc5c43bbd6cb.png)

**Describe the solution you'd like**

See `src/routes/activities/components/form/_What.svelte` for an example

```
<div class="relative">
  <span
    class="absolute top-0 left-0 transform -translate-x-4 -translate-y-4 block h-2 w-2 rounded-full bg-red-400">
  </span>
</div>
```

https://github.com/ThatConference/that.us/blob/master/src/routes/activities/components/form/_What.svelte#L15-L19

**Comment by himanshu007-creator** [comment]
hi, i would like to work on this issue

**Comment by csell5** [comment]
@himanshu007-creator it's all yours! Thank you. If you need any help or have questions please let me know.

**Comment by csell5** [comment]
@himanshu007-creator sorry, I couldn't wait any longer and needed to get this through.

**Comment by himanshu007-creator** [comment]
> @himanshu007-creator sorry, I couldn't wait any longer and needed to get this through.

Its totally understandable, I had exams + other stuff going on. But nevermind, I will look into future issues😊
