### ISSUE TITLE
Takeaways seem to be removed on update, when not touched.

### ISSUE THREAD

**Issue by csell5** [ThatConference/that.us#816]
**Describe the bug**
It appears the takeaway and resources section is being cleared on update.

**To Reproduce**
1. pick an existing session, with takeaways
2.  update something other than takeaways
3.  save
4. return to it.

**Expected behavior**
existing data should be passed through.

**Comment by zo0o0ot** [comment]
That sounds accurate.  I had the takeaways saved in a different place, so it wasn't a huge loss to me.  When the edit submission page came up, I made the erroneous assumption that if they weren't shown, they wouldn't be changed.

So, the initial issue was that the existing takeaways didn't load when I opened the edit page (but everything else did), then I saved those changes, and probably blew any existing takeaways away.
