### ISSUE TITLE
Mobile checkin doesn't show ticket type or pin, Button covers Name

### ISSUE THREAD

**Issue by brettski** [ThatConference/that.us#853]
**Describe the bug**
When running checkin from a mobile device the ticket type doesn't display.

**To Reproduce**
1. From a mobile device go to, /event/wi/2021/checkin
2. For each person in the list, notice there is no ticket type listed.
3. for each person in the list notice there is no pin or pin status listed

**Expected behavior**
A ticket type is required to check someone to allow the volunteer to provide proper swag, etc.

**Comment by zaudtke** [comment]
I added a couple more related to checkin on mobile.  Looking a bit closer, all of them are on my phone, not an iPad.  I have an iPhone SE so not super huge.

Additionally, I only used my phone 1 time to do a checkin.  It was for a specific person that purchased a last minute Pig Roast ticket and found me to checkin after we closed down registration, and no larger devices were readily available.  I'm not sure if that will be a common use case, but it is what lead to these items.

**Comment by zaudtke** [comment]
Adding details from #857 as it makes sense to be at the same time as this.

When running checkin from a smaller mobile device (phone portrait) and you go to the Order View toggle. When expanding to view the tickets, the button to either Check-in or Edit Checkin covers the ticket holders name.
