### ISSUE TITLE
UserProfile Drop Down z-index wrong

### ISSUE THREAD

**Issue by csell5** [ThatConference/that.us#868]
The bottom two items in the user profile dropdown are under the header on /events/tx/2022. z-index seems to be set right, but yet it's covered.

**Comment by AndrewSchwabe** [comment]
This is an issue for both of the hybrid events currently on the site:
![image](https://user-images.githubusercontent.com/17070695/146628252-2945684f-d2df-4746-835f-d3913f31209f.png)
![image](https://user-images.githubusercontent.com/17070695/146628264-e716c62e-630d-4e41-82f5-484c212771c2.png)

**Comment by AndrewSchwabe** [comment]
@csell5 I am unable to assign this issue to myself, is that intentional?

**Comment by csell5** [comment]
@AndrewSchwabe it's just the way github works. Once you comment on it, I can assign it to ya. And thank you for picking this up!

**Comment by AndrewSchwabe** [comment]
@csell5 unless there is something else, this issue is resolved in production.

![image](https://user-images.githubusercontent.com/17070695/147031221-99c2c9d5-9f87-4fe4-8c9e-8890799c66f0.png)

**Comment by csell5** [comment]
I'm not sure why the PR didn't get linked and close this. On it. thanks for pointing it ou.
