### ISSUE TITLE
Shared profile is requiring City and State

### ISSUE THREAD

**Issue by brettski** [ThatConference/that.us#885]
**Describe the bug**
When updating "Shared Profile" an error is thrown when city and state is not filled in. They are optional fields.
Note: If I go back and remove the values, I can then save those fields as empty. Perhaps they are getting an invalid initial value on first visit to "Shared Profile"

**To Reproduce**
1. On a new account go to User Profiles
2. Click on Shared Profile
3. Update some field but DON'T update **City** or **State**
4. Click Save
5. The City and State fields are in error requiring a value (see visual aid)
6. Based on the error, the field values are `null` which isn't valid

Please note: If you add a value, save, then remove that value, you are able to save the fields as blank, so obviously an issue with the `null` in the field

**Expected behavior**
City and state are not required and thus shouldn't need to be filled in

**Screenshots**
![image](https://user-images.githubusercontent.com/473633/133330145-038b07ee-30f5-4a51-8152-ed283b368dff.png)

**Comment by csell5** [comment]
@brettski can you please retest this?
