### ISSUE TITLE
Unauthenticated user gets stuck creating Activity

### ISSUE THREAD

**Issue by brettski** [ThatConference/that.us#888]
**Describe the bug**
An unauthenticated user is stuck on a loading screen when the click to add an Activity

**To Reproduce**
1. Go to that.us
2. Click on "+" plus sign in upper right
3. You are brought to a loading screen and stay there

This appears to happen from any link or button pointing to `/activities/create` when an unauthorized user. 

**Expected behavior**
A message should be displayed letting the user know they must be logged in. Secondary information of having a completed profile which is public may be useful. 

**Screenshots**
Screen stops here:  
[![Screen](https://i.gyazo.com/2db1510978ca4b0557da457447a7ddb8.gif)](https://gyazo.com/2db1510978ca4b0557da457447a7ddb8)

**Comment by csell5** [comment]
fixed in a big ass way.
