### ISSUE TITLE
User able to create activity with unverified account

### ISSUE THREAD

**Issue by brettski** [ThatConference/that.us#889]
**Describe the bug**
A user with an unverified account, unverified email address is able to create an activity

**To Reproduce**
1. Using a user with an unverified email address and a complete profile go to `/activities/create`
2. Choose an event, for example, *Daily THAT*
3. Complete the form to create the activity and submit it
4. You successfully create a new activity in the site

**Expected behavior**
Users with unverified accounts should not be able to get to or use the `/activities/create` page

I validated that this still works in the live site providing the following message:  
`that.us/verify-account`. 
![image](https://user-images.githubusercontent.com/473633/133627546-98838708-6f3a-410b-aa48-638609e456fe.png)

**Comment by csell5** [comment]
better yet.. all of the accont verification was accidently removed with the router being replaced. whoops.

**Comment by csell5** [comment]
fixed
