### ISSUE TITLE
Events not being removed correctly from Activity Create

### ISSUE THREAD

**Issue by brettski** [ThatConference/that.us#891]
**Describe the bug**
It is now September 16th, 2021 @ 11:54 CDT. When going to the event create page the September event is still listed AND I am able to add an Activity to it. THAT Online - September has the following db settings:

- startDate: September 15, 2021 at 06:00:00 UTC-5
- endDate: September 16, 2021 at 06:00:00 UTC-5

**Note:** This appears the same in _production_

**Expected behavior**
The event should not be displaying on the create page as an available event to add an Activity to. 

**Screenshots**
<img src="https://user-images.githubusercontent.com/473633/133655072-6c397d24-41ef-4342-8d5a-3ee121c9188e.png" height=300 />

**Comment by csell5** [comment]
Currently works like that today, so exisitng. but techically the event ended earlier today. So it's sorta working as designed. It needs to have a higer resolution to hour vs just day.
