### ISSUE TITLE
Unable to remove favorite from /my/favorites page

### ISSUE THREAD

**Issue by brettski** [ThatConference/that.us#896]
**Describe the bug**
When trying to remove a favorite activity from `/my/favorites`, nothing happens and an error is thrown in console:
```text
POST https://gateway-bgydxslf5a-uc.a.run.app/ 400
```

**To Reproduce**
1. If you have not future active activities, go favorite one
2. under your profile go to **My Favorites**
3. Click the ❤️ Favorite button to unfavorite on of your favorited activities
4. Notice the activity does not un-favorite
5. See error `POST https://gateway-bgydxslf5a-uc.a.run.app/ 400` in web console

This was tested as working in current production

**Expected behavior**
The activity should be removed from your favorites list

**Comment by csell5** [comment]
This page and the api need another rev. We need to be able to pull all favorites across all events. of course, that should be able to be paged, sorted, searched.. and I am sure a few other things. For me who has favorited a lot.. it's a perf disaster and it's missing other events outside the default.
