### ISSUE TITLE
/my/network/sponsors not loading

### ISSUE THREAD

**Issue by brettski** [ThatConference/that.us#905]
**Describe the bug**
the page, `/my/netwok/sponsors` doesn't load. Throws error in console

**To Reproduce**
1. login to that.us
2. click your profile picture and go down to "My Network"
3. The My network page doesn't display data. Looking in console see the error:
```text
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'firstName')
    at create_each_block (sponsors.svelte? [sm]:49)
    at create_then_block (sponsors.svelte? [sm]:38)
    at update2 (index.mjs:1349)
    at index.mjs:1384
```

No error is thrown if you haven't met any sponsors. There should be a message saying, "You have not connected with any sponsor yet" if there are no records. In stead of an empty area on the page. 

**Expected behavior**
Page should load showing scanned data or no data when there are no scans

**Comment by csell5** [comment]
fixed.
