### ISSUE TITLE
Show feedback after session creation

### ISSUE THREAD

**Issue by GeekOnCoffee** [ThatConference/that.us#92]
Currently, creating a session drops you at the top of the schedule. Ideally it should at least show a confirmation that it completed it, or even jump you to it on the schedule

**Comment by csell5** [comment]
What if I just took you to your list of submitted sessions?

**Comment by GeekOnCoffee** [comment]
That would be an improvement

**Comment by csell5** [comment]
Fixed... We redirect back to the session detail after a session is created.
