### ISSUE TITLE
This looks purpley maybe, should we use brand colors for buttons, text, svgs

### ISSUE THREAD

**Issue by saragibby** [ThatConference/that.us#98]
<img width="1321" alt="that_us" src="https://user-images.githubusercontent.com/82035/87736212-931e7700-c7a5-11ea-9c69-22cdbaeb82fa.png">

**Comment by csell5** [comment]
yea we damn sure should.. haven't gotten too any that yet.

**Comment by csell5** [comment]
Fixed.
